replicaCount: 2
image:
  repository: ""
  tag: ""
  pullPolicy: Always
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
service:
  type: ClusterIP
  port: 3000
  livenessProbe: /ping
  readinessProbe: /ping
serviceAccount:
  create: false
autoscaling:
  enabled: false
ingress:
  enabled: false
env: