replicaCount: 2
image:
  repository: ""
  tag: ""
  pullPolicy: Always
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: false
autoscaling:
  enabled: false
ingress:
  enabled: false
env: