apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: kaniko-build-and-push-pipeline
  namespace: tekton
spec:
  workspaces:
  - name: shared-workspace
  tasks:
  - name: git-clone
    taskRef:
      name: git-clone # from kubectl apply -f https://raw.githubusercontent.com/tektoncd/catalog/main/task/git-clone/0.9/git-clone.yaml
    params:
    - name: URL
      value: {{GIT_URL}}
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: kaniko-build-and-push-task
    taskRef:
      name: kaniko # from https://raw.githubusercontent.com/tektoncd/catalog/main/task/kaniko/0.6/kaniko.yaml
    params:
    - name: IMAGE
      value: {{IMAGE}}
    - name: DOCKERFILE
      value: {{DOCKERFILE}}
    - name: CONTEXT
      value: {{CONTEXT}}
    runAfter:
    - git-clone
    workspaces:
    - name: workspace
      workspace: shared-workspace
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: kaniko-build-and-push-pipelinerun
  namespace: tekton
spec:
  pipelineRef:
    name: kaniko-build-and-push-pipeline
