apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: psql-migrate-database-pipeline-run
  namespace: tekton
spec:
  pipelineSpec:
    tasks:
      - name: task
        taskSpec:
          steps:
            - name: step
              image: governmentpaas/psql
              script: |
                echo '{{ENCODED_QUERY}}' | base64 -d | psql {{POSTGRES_CONNECTION_STRING}}
