kind: Namespace
apiVersion: v1
metadata:
  name: windmill
  labels:
    name: windmill
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: windmill
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: windmill
    server: https://kubernetes.default.svc
  orphanedResources:
    warn: false
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: windmill
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: windmill
  project: windmill
  source:
    repoURL: https://github.com/windmill-labs/windmill-helm-charts.git
    targetRevision: main
    path: ./charts/windmill
    helm:
      values: |
        windmill:
          appReplicas: 1
          workerReplicas: 1
          lspReplicas: 1
          databaseUrl: postgres://postgres:{{POSTGRES_PASSWORD}}@postgresql.postgresql.svc/windmill?sslmode=disable
        postgresql:
          enabled: false
